#!/bin/bash
sudo ./led-image-viewer --led-gpio-mapping=adafruit-hat --led-slowdown-gpio=2 --led-rows=32 --led-cols=64 --led-limit-refresh=80 --led-chain=2 --led-pixel-mapper="U-mapper;Rotate:270" -C ../img/*.jpg
